-- MySQL Script generated by MySQL Workbench
-- Wed Sep 21 18:20:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbz5
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbz5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbz5` DEFAULT CHARACTER SET utf8 ;
USE `dbz5` ;

-- -----------------------------------------------------
-- Table `dbz5`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbz5`.`test` (
  `idtest` INT NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(255) NOT NULL,
  `prijmeni` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `pohlavi` VARCHAR(255) NOT NULL,
  `os` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idtest`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
